### ISSUE TITLE
Error building DependencyGraph:  Error: Naming collision detected:

### ISSUE THREAD

**Issue by lucasfeliciano** [ericvicenti/navigation-rfc#14]
I installed `navigation-rfc` through `npm install https://github.com/ericvicenti/navigation-rfc`

After that I created an `app.js` which is NOT included to `index.ios.js` yet.
You can find the content of `app.js` below.

``` javascript
'use strict';

var NavigationContainer = require('navigation-rfc/Navigation/NavigationContainer');
var NavigationReducer = require('navigation-rfc/Navigation/NavigationReducer');
var NavigationState = require('navigation-rfc/Navigation/NavigationState');

var React = require('react-native');

var {
  Text
} = React;

var App = React.createClass({
  render: function() {
    return (
      <NavigationContainer.RootContainer
      initialState={new NavigationState(['first page'], 0)}
      reducer={NavigationReducer}
      renderNavigator={(navState, onNavigation) => (
        <View>
          <Text>Current page: {navState.get(navState.index)}</Text>
          <Text
            onPress={() => {
              onNavigation(new NavigationReducer.Actions.Push('page #' + navState.size));
            }}>
            Push page #{navState.size}
          </Text>
          <Text
            onPress={() => {
              onNavigation(new NavigationReducer.Actions.Pop());
            }}>
            Pop
          </Text>
          <Text onPress={this.props.onExampleExit}>Exit Basic Nav Example</Text>
        </View>
      )}
      />
    );

  }
});

module.exports = App;
```

Then I tried to build my project but it is failing throwing this exception in the terminal

```
[1:29:16 PM] <END>   Building (deprecated) Asset Map (115ms)
Error building DependencyGraph:
 Error: Naming collision detected: /Users/myUser/Projects/MyProject/node_modules/navigation-rfc/node_modules/react-native/Libraries/Promise.js collides with /Users/myUser/Projects/MyProject/node_modules/react-native/Libraries/Promise.js
    at HasteMap._updateHasteMap (HasteMap.js:123:13)
    at HasteMap.js:94:28
    at tryCallOne (/Users/myUser/Projects/MyProject/node_modules/promise/lib/core.js:37:12)
    at /Users/myUser/Projects/MyProject/node_modules/promise/lib/core.js:123:15
    at flush (/Users/myUser/Projects/MyProject/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:456:9)
    at process._tickCallback (node.js:385:13)
Thu, 14 Jan 2016 12:29:16 GMT ReactNativePackager:SocketServer exit code: 1

    at terminate (SocketClient.js:59:17)
    at Socket.<anonymous> (SocketClient.js:74:37)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1256:8)
    at nextTickCallbackWith2Args (node.js:478:9)
    at process._tickCallback (node.js:392:17)
```

I know it is a dependency conflict but it is the first time that I get that so I don't know how to approach this issue.

**Comment by lucasfeliciano** [comment]
Managed to make it working by downloading the navigation files and adding them manually into my project :)

**Comment by ericvicenti** [comment]
Ah, sorry about these troubles! It should be easier when this stuff makes it into the react native repo
